/**
 * Copy WakeAgain web client into Capacitor www/ for Play Store & App Store.
 * - Full public/ mirror for shared pages
 * - App shell paths rewritten for Capacitor file loading
 * - runtime-config.js injects WAKEAGAIN_API_BASE
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..", "..");
const publicDir = path.join(root, "public");
const www = path.join(__dirname, "..", "www");
const mobileRoot = path.join(__dirname, "..");

function rimraf(dir) {
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
}

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const name of fs.readdirSync(src)) {
    if (name === ".DS_Store") continue;
    const s = path.join(src, name);
    const d = path.join(dest, name);
    if (fs.statSync(s).isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function rewriteAppShell(html) {
  let out = html;
  // runtime config + native bridge before api.js
  if (!out.includes("runtime-config.js")) {
    out = out.replace(
      /<script src="\/js\/api\.js"><\/script>/,
      '<script src="../js/runtime-config.js"></script>\n  <script src="../js/api.js"></script>\n  <script src="../js/native-bridge.js"></script>'
    );
  }
  // absolute → relative for packaged app
  const pairs = [
    ['href="/styles.css"', 'href="../styles.css"'],
    ['href="/ux9.css"', 'href="../ux9.css"'],
    ['href="/app/app.css"', 'href="app.css"'],
    ['href="/favicon.ico"', 'href="../favicon.ico"'],
    ['href="/favicon.svg"', 'href="../favicon.svg"'],
    ['href="/manifest.webmanifest"', 'href="../manifest.webmanifest"'],
    ['src="/js/', 'src="../js/'],
    ['src="/app/app.js"', 'src="app.js"'],
    ['href="/app/"', 'href="./index.html"'],
    ['href="/app/#', 'href="./index.html#'],
    ['href="/buy.html"', 'href="../buy.html"'],
    ['href="/sell.html"', 'href="../sell.html"'],
    ['href="/legal/', 'href="../legal/'],
    ['href="/guide/', 'href="../guide/'],
    ['href="/showcase.html"', 'href="../showcase.html"'],
    ['href="/showcase-new.html"', 'href="../showcase-new.html"'],
    ['href="/diagnose.html"', 'href="../diagnose.html"'],
    ['href="/project.html', 'href="../project.html'],
    ['href="/review.html"', 'href="../review.html"'],
    ['href="/"', 'href="../index.html"'],
  ];
  for (const [a, b] of pairs) {
    out = out.split(a).join(b);
  }
  // viewport safe area for notched phones
  if (!out.includes("viewport-fit=cover")) {
    out = out.replace(
      'width=device-width, initial-scale=1',
      'width=device-width, initial-scale=1, viewport-fit=cover'
    );
  }
  return out;
}

function rewriteHtmlFile(filePath, isAppShell) {
  if (!fs.existsSync(filePath)) return;
  let html = fs.readFileSync(filePath, "utf8");
  if (isAppShell) {
    html = rewriteAppShell(html);
  } else {
    // secondary pages: inject runtime config if they load api.js
    if (html.includes('src="/js/api.js"') && !html.includes("runtime-config.js")) {
      html = html.replace(
        '<script src="/js/api.js"></script>',
        '<script src="/js/runtime-config.js"></script>\n  <script src="/js/api.js"></script>'
      );
    }
    // For capacitor, absolute / paths often break — keep as root-relative
    // when opened via redirect from www/index; secondary pages still use / when
    // served from same origin. Capacitor WebView loads from capacitor://localhost
    // so we convert leading / to relative from www root for common assets.
    html = html
      .replaceAll('href="/styles.css"', 'href="styles.css"')
      .replaceAll('href="/favicon', 'href="favicon')
      .replaceAll('src="/js/', 'src="js/')
      .replaceAll('href="/legal/', 'href="legal/')
      .replaceAll('href="/guide/', 'href="guide/')
      .replaceAll('href="/app/', 'href="app/')
      .replaceAll('href="/"', 'href="index.html"');
  }
  fs.writeFileSync(filePath, html, "utf8");
}

// --- run ---
if (!fs.existsSync(publicDir)) {
  console.error("public/ not found:", publicDir);
  process.exit(1);
}

rimraf(www);
copyDir(publicDir, www);

// API host for native builds (required for store / device)
// Dev Android emulator default: 10.0.2.2 → host localhost
// Production: set WAKEAGAIN_API_BASE=https://api.yourdomain.com
const apiBase =
  process.env.WAKEAGAIN_API_BASE ||
  process.env.CAPACITOR_API_BASE ||
  "http://10.0.2.2:8080";

const jsDir = path.join(www, "js");
fs.mkdirSync(jsDir, { recursive: true });

const cfg = `/* generated by sync-www.js — do not edit */
window.WAKEAGAIN_API_BASE = ${JSON.stringify(apiBase)};
window.WAKEAGAIN_CHANNEL = "native";
window.WAKEAGAIN_APP_VERSION = ${JSON.stringify(
  require(path.join(mobileRoot, "package.json")).version || "0.1.0"
)};
`;
fs.writeFileSync(path.join(jsDir, "runtime-config.js"), cfg, "utf8");

// native bridge (StatusBar / Splash) — no bundler
const bridgeSrc = path.join(__dirname, "native-bridge.js");
if (fs.existsSync(bridgeSrc)) {
  fs.copyFileSync(bridgeSrc, path.join(jsDir, "native-bridge.js"));
} else {
  fs.writeFileSync(
    path.join(jsDir, "native-bridge.js"),
    "/* native-bridge missing */\n",
    "utf8"
  );
}

// Capacitor entry → app shell
const redirect = `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="theme-color" content="#050508" />
  <title>WakeAgain</title>
  <script>location.replace('app/index.html' + (location.hash || ''));</script>
  <meta http-equiv="refresh" content="0;url=app/index.html" />
</head>
<body style="background:#050508;color:#fff;font-family:system-ui;padding:2rem;text-align:center">
  <p>WakeAgain 시작 중…</p>
  <p><a href="app/index.html" style="color:#c084fc">앱 열기</a></p>
</body>
</html>
`;
fs.writeFileSync(path.join(www, "index.html"), redirect, "utf8");

// rewrite app shell
rewriteHtmlFile(path.join(www, "app", "index.html"), true);

// rewrite key secondary pages for relative assets
for (const rel of [
  "buy.html",
  "sell.html",
  "diagnose.html",
  "showcase.html",
  "showcase-new.html",
  "project.html",
  "review.html",
  "guide/index.html",
  "legal/terms.html",
  "legal/privacy.html",
]) {
  rewriteHtmlFile(path.join(www, rel), false);
}

console.log("synced public → mobile/www");
console.log("WAKEAGAIN_API_BASE =", apiBase);
if (!process.env.WAKEAGAIN_API_BASE && !process.env.CAPACITOR_API_BASE) {
  console.log(
    "(tip) 스토어 빌드 전: set WAKEAGAIN_API_BASE=https://your-api.example"
  );
}
